#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$ROOT/.agents/skills"
CLAUDE_LINK="$ROOT/.claude/skills"
CURSOR_LINK="$ROOT/.cursor/skills"
ROOT_LINK="$ROOT/skills"
GEMINI_COMMANDS_DIR="$ROOT/.gemini/commands"

usage() {
  echo "Usage: sync-agent-skills.sh [--check|--sync-aliases|--check-aliases]" >&2
  exit 2
}

ensure_link() {
  local target="$1"
  local link="$2"
  mkdir -p "$(dirname "$link")"
  rm -rf "$link"
  ln -s "$target" "$link"
}

check_link() {
  local target="$1"
  local link="$2"
  local actual

  [[ -L "$link" ]] || { echo "$link missing symlink" >&2; exit 1; }
  actual="$(readlink "$link")"
  if [[ "$actual" != "$target" ]]; then
    echo "$link points to '$actual' (expected '$target')" >&2
    exit 1
  fi
}

render_alias() {
  local name="$1"
  cat <<EOF
# Generated by scripts/sync-agent-skills.sh. Do not edit manually.
name = "$name"
prompt = "/$name \$ARGUMENTS"
EOF
}

write_alias() {
  local name="$1"
  render_alias "$name" > "$GEMINI_COMMANDS_DIR/$name.toml"
}

sync_aliases() {
  mkdir -p "$GEMINI_COMMANDS_DIR"
  find "$GEMINI_COMMANDS_DIR" -maxdepth 1 -name '*.toml' -delete
  while IFS= read -r skill_file; do
    local skill_dir
    local name
    skill_dir="$(dirname "$skill_file")"
    name="$(basename "$skill_dir")"
    write_alias "$name"
  done < <(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name 'SKILL.md' | sort)
}

check_mode() {
  local skill_count
  check_link "../.agents/skills" "$CLAUDE_LINK"
  check_link "../.agents/skills" "$CURSOR_LINK"
  check_link ".agents/skills" "$ROOT_LINK"
  skill_count="$(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name 'SKILL.md' | wc -l | tr -d ' ')"
  if [[ "$skill_count" == "0" ]]; then
    echo "No canonical skills found in .agents/skills" >&2
    exit 1
  fi
  echo "skills-check: OK ($skill_count canonical skills; compatibility links ok; command aliases optional)"
}

check_aliases() {
  local skill_count alias_count skill_file skill_dir name out_file expected actual
  skill_count="0"
  while IFS= read -r skill_file; do
    skill_dir="$(dirname "$skill_file")"
    name="$(basename "$skill_dir")"
    out_file="$GEMINI_COMMANDS_DIR/$name.toml"
    [[ -f "$out_file" ]] || { echo "Missing command alias: $out_file" >&2; exit 1; }
    expected="$(render_alias "$name")"
    actual="$(cat "$out_file")"
    if [[ "$actual" != "$expected" ]]; then
      echo "Command alias content drifted: $out_file" >&2
      exit 1
    fi
    skill_count=$((skill_count + 1))
  done < <(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name 'SKILL.md' | sort)
  if [[ -d "$GEMINI_COMMANDS_DIR" ]]; then
    alias_count="$(find "$GEMINI_COMMANDS_DIR" -maxdepth 1 -name '*.toml' | wc -l | tr -d ' ')"
  else
    alias_count="0"
  fi
  if [[ "$skill_count" != "$alias_count" ]]; then
    echo "Alias count mismatch: $skill_count skills, $alias_count command aliases" >&2
    exit 1
  fi
  echo "alias-check: OK ($skill_count skills, $alias_count command aliases)"
}

if [[ "${1:-}" == "--help" ]]; then
  usage
fi

if [[ "${1:-}" == "--check" ]]; then
  check_mode
  exit 0
fi

if [[ "${1:-}" == "--sync-aliases" ]]; then
  sync_aliases
  check_aliases
  exit 0
fi

if [[ "${1:-}" == "--check-aliases" ]]; then
  check_aliases
  exit 0
fi

if [[ $# -gt 0 ]]; then
  usage
fi

ensure_link "../.agents/skills" "$CLAUDE_LINK"
ensure_link "../.agents/skills" "$CURSOR_LINK"
ensure_link ".agents/skills" "$ROOT_LINK"
check_mode
