#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_DIR="$ROOT/.agents/skills"
CLAUDE_LINK="$ROOT/.claude/skills"
CURSOR_LINK="$ROOT/.cursor/skills"
ROOT_LINK="$ROOT/skills"
GEMINI_DIR="$ROOT/.gemini/commands"

usage() {
  echo "Usage: sync-agent-skills.sh [--check]" >&2
  exit 2
}

ensure_link() {
  local target="$1"
  local link="$2"
  mkdir -p "$(dirname "$link")"
  rm -rf "$link"
  ln -s "$target" "$link"
}

write_wrapper() {
  local name="$1"
  cat > "$GEMINI_DIR/$name.toml" <<EOF
# Generated by scripts/sync-agent-skills.sh. Do not edit manually.
name = "$name"
prompt = "/$name \$ARGUMENTS"
EOF
}

sync_wrappers() {
  mkdir -p "$GEMINI_DIR"
  find "$GEMINI_DIR" -maxdepth 1 -name '*.toml' -delete
  while IFS= read -r skill_file; do
    local skill_dir
    local name
    skill_dir="$(dirname "$skill_file")"
    name="$(basename "$skill_dir")"
    write_wrapper "$name"
  done < <(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name 'SKILL.md' | sort)
}

check_mode() {
  local skill_count wrapper_count
  [[ -L "$CLAUDE_LINK" ]] || { echo ".claude/skills missing symlink" >&2; exit 1; }
  [[ -L "$CURSOR_LINK" ]] || { echo ".cursor/skills missing symlink" >&2; exit 1; }
  [[ -L "$ROOT_LINK" ]] || { echo "skills missing symlink" >&2; exit 1; }
  skill_count="$(find "$SKILLS_DIR" -mindepth 2 -maxdepth 2 -name 'SKILL.md' | wc -l | tr -d ' ')"
  wrapper_count="$(find "$GEMINI_DIR" -maxdepth 1 -name '*.toml' | wc -l | tr -d ' ')"
  if [[ "$skill_count" != "$wrapper_count" ]]; then
    echo "Wrapper count mismatch: $skill_count skills, $wrapper_count wrappers" >&2
    exit 1
  fi
  echo "skills-check: OK ($skill_count skills, $wrapper_count gemini wrappers)"
}

if [[ "${1:-}" == "--help" ]]; then
  usage
fi

if [[ "${1:-}" == "--check" ]]; then
  check_mode
  exit 0
fi

if [[ $# -gt 0 ]]; then
  usage
fi

ensure_link "../.agents/skills" "$CLAUDE_LINK"
ensure_link "../.agents/skills" "$CURSOR_LINK"
ensure_link ".agents/skills" "$ROOT_LINK"
sync_wrappers
check_mode

